spring:
  cloud:
    nacos:
      discovery:
        server-addr: prod:8848
        username: nacos
        password: nacos
        namespace: spring-cloud-demo
        group: ${spring.profiles.active}
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
  redis:
    host: prod
    database: 1
    port: 6379
    password: prod
    timeout: 3000ms
    lettuce:
      pool:
        enabled: true
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: 180000