spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: test
        group: test
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true