spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

common:
  skipUrl: /base/login,/base/register,/base/logout,/base/image/captcha,/base/publicKey