server:
  port: 9080

spring:
  application:
    name: gateway-server
  profiles:
    active: local
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  config:
    import: nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
  cloud:
    nacos:
      config:
        username: nacos
        password: nacos
        server-addr: localhost:8848
        namespace: spring-cloud-demo
        file-extension: yml
        group: DEFAULT_GROUP