spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: spring-cloud-demo
        group: local
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
  redis:
    host: localhost
    database: 1
    port: 6379
    password: mengwei131575585
    timeout: 3000ms
    lettuce:
      pool:
        enabled: true
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: 180000