spring:
  cloud:
    nacos:
      discovery:
        server-addr: prod:8848
        username: nacos
        password: nacos
        namespace: prod
        group: prod
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true