server:
  port: 9081

spring:
  application:
    name: system-server
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        namespace: spring-cloud-demo
        file-extension: yml
        group: DEFAULT_GROUP
        server-addr: localhost:8848
  config:
    import: nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true