spring:
  cloud:
    nacos:
      discovery:
        server-addr: dev:8848
        username: nacos
        password: nacos
        namespace: spring-cloud-demo
        group: ${spring.profiles.active}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dev:3306/spring_cloud_demo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: test
  redis:
    host: dev
    database: 1
    port: 6379
    password: test
    timeout: 3000ms
    lettuce:
      pool:
        enabled: true
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: 180000
  kafka:
    bootstrap-servers: test:9092
    listener:
      missing-topics-fatal: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: spring_cloud_demo_group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  cache:
    redis:
      use-key-prefix: false

dubbo:
  application:
    name: ${spring.application.name}-provider
  registry:
    address: nacos://${spring.cloud.nacos.discovery.server-addr}
    username: nacos
    password: nacos
    use-as-config-center: false
    use-as-metadata-center: false
    parameters:
      namespace: ${spring.cloud.nacos.discovery.namespace}
      group: ${spring.cloud.nacos.discovery.group}
  protocol:
    name: dubbo
    port: -1
  consumer:
    check: false