spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

common:
  skip-url:
    [
      /base/login,
      /base/register,
      /base/image/captcha,
      /swagger-ui/**,
      /swagger-ui.html,
      /swagger-resources/**,
      /v2/api-docs,
      /v3/api-docs
    ]